version: '3.8'
services:
  api:
    env_file:
      - .env
    container_name: prestamo_api_development
    image: prestamo_api_dev:0.0.1

    build:
      context: ./api
    ports:
      - '3030:3030'
    volumes:
      - ./api:/app
      
    command: ./docker-entrypoint.sh
    depends_on:
      prestamo_db:
        condition: service_healthy

  prestamo_db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - '$DB_PORT:$LOCAL_DB_PORT'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db: {}
